tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/services"
tap "nodenv/nodenv"
tap "ringohub/redis-cli"
tap "samtay/tui"
tap "thecasualcoder/stable"
brew "ack"
brew "aspell"
brew "atlas"
brew "awk"
brew "openssl@3"
brew "bat"
brew "brew-cask-completion"
brew "sqlite"
brew "clipboard"
brew "curl"
brew "php"
brew "composer"
brew "coreutils"
brew "diff-so-fancy"
brew "docker"
brew "exiftool"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "gawk"
brew "gcc"
brew "geckodriver"
brew "git"
brew "go"
brew "ncurses"
brew "htop"
brew "httpie"
brew "jenv"
brew "jq"
brew "lazygit"
brew "lsd"
brew "lynx"
brew "lua"
brew "luarocks"
brew "make"
brew "mas"
brew "mercurial"
brew "mkcert"
brew "mongosh"
brew "mongodb-atlas-cli"
brew "neovim"
brew "tree-sitter", args: ["HEAD"]
brew "nmap"
brew "node-build"
brew "nodenv"
brew "openssh"
brew "pass"
brew "poppler"
brew "pdfgrep"
brew "peco"
brew "pipx"
brew "pipenv"
brew "powerlevel10k"
brew "pyenv"
brew "pyenv-pip-migrate"
brew "pyenv-virtualenv"
brew "ranger"
brew "rbenv"
brew "ripgrep"
brew "rust"
brew "rustup"
brew "speedtest-cli"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tor"
brew "vim"
brew "wget"
brew "wireshark"
brew "yarn"
brew "z"
brew "zoxide"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "ringohub/redis-cli/redis-cli"
brew "samtay/tui/tetris"
brew "thecasualcoder/stable/csvdiff"
cask "alacritty"
cask "chromedriver"
cask "discord"
cask "fission"
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-powerline-symbols"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "kitty"
cask "ngrok"
cask "notion"
cask "onedrive"
cask "postman"
cask "quarto"
cask "r"
cask "rstudio"
cask "rectangle"
cask "redisinsight"
cask "temurin@11"
cask "temurin@17"
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Anybox", id: 1593408455
mas "BetterSnapTool", id: 417375580
mas "Find Any File", id: 402569179
mas "Hush", id: 1544743900
mas "JSONPeep", id: 1458969831
mas "Menu Bar Calendar", id: 1558360383
mas "Numbers", id: 409203825
mas "Octotree", id: 1457450145
mas "Postman Interceptor", id: 6460587883
mas "ProFind", id: 1441703569
mas "Spect", id: 1409975750
mas "TickTick", id: 966085870
mas "Web(Cache)Browser", id: 432802024
mas "Webcam Recorder", id: 1508067444
