include gruvbox-kitty.conf

shell .
editor .
close_on_child_death no
term xterm-256color
remote_kitty if-needed
enabled_layouts splits
enable_audio_bell no
enable_alternate_screen_buffer true
underline_hyperlinks hover
macos_titlebar_color background
font_family      JetBrains Mono Medium
# font_family Hack Nerd Font Mono
# font_family MesloLGS NF
bold_font        auto
italic_font      auto
bold_italic_font auto
cursor_shape block
cursor_blink_interval 0
# cursor_beam_thickness 2.5
font_size 14.0
scrollback_lines 8000
share_connections yes
mouse_map left click ungrabbed no-op
mouse_map ctrl+left click ungrabbed mouse_handle_click selection link prompt
mouse_map ctrl+left press ungrabbed mouse_selection normal
mouse_map right press ungrabbed copy_to_clipboard
remember_window_size  yes
tab_bar_style powerline
background_opacity 1.0
allow_remote_control yes
shell_integration no-cursor no-title

kitty_mod ctrl+shift

map cmd+c        copy_to_clipboard
map cmd+v        paste_from_clipboard
map shift+insert paste_from_clipboard
map kitty_mod+enter no-op
map cmd+enter       no-op
copy_on_select yes

mouse_map ctrl+left press ungrabbed,grabbed mouse_click_url

macos_option_as_alt no

# disable tabs
map kitty_mod+t no_op

bind "[101;9u" edit_command_buffer

map cmd+q quit

disable_ligatures always
font_features none
sync_to_monitor yes
visual_bell_color none
window_alert_on_bell no
bell_on_tab ""
command_on_bell none
confirm_os_window_close 0
strip_trailing_spaces smart
select_by_word_characters_forward
allow_hyperlinks yes
macos_quit_when_last_window_closed yes
macos_traditional_fullscreen yes

map kitty_mod+f11 toggle_fullscreen
map kitty_mod+f10 toggle_maximized
map kitty_mod+f5 load_config_file
map ctrl+cmd+,   load_config_file

include grovbox-kitty.conf
