general.import = ["~/.config/alacritty/themes-alacritty/gruvbox_dark.toml"]

general.live_config_reload = true

[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[colors.cursor]
text = "#282828"
cursor = "#ebdbb2"

[colors.selection]
text = "#282828"
background = "#ebdbb2"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13.5
offset = {x = 1, y = 0}
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
bold = { family = "MesloLGS Nerd Font Mono", style = "Bold" }
italic = { family = "MesloLGS Nerd Font Mono", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font Mono", style = "Bold Italic" }

[[keyboard.bindings]]
key = "Up"
mods = "Command"
chars = "\u001B[5~"
mode = "~Vi|~Search"

[[keyboard.bindings]]
key = "Down"
mods = "Command"
chars = "\u001B[6~"
mode = "~Vi|~Search"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001BOH"
mode = "~Vi|~Search"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001BOF"
mode = "~Vi|~Search"

[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[scrolling]
history = 100000

[window]
decorations = "full"
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
dynamic_title = false
padding = {x = 1, y = 1}
dimensions = {columns = 150, lines = 50}
title = "Alacritty"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"
