import = ["~/.config/alacritty/base16-gruvbox-dark-hard.toml"]

live_config_reload = true

[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

# [font.bold]
# family = "Hack Nerd Font Mono"
# style = "Bold"

# [font.bold_italic]
# family = "Hack Nerd Font Mono"
# style = "Bold Italic"

# [font.italic]
# family = "Hack Nerd Font Mono"
# style = "Italic"

# [font.normal]
# family = "Hack Nerd Font Mono"
# style = "Regular"

# [font.offset]
# x = 2  # compacter letter spacing
# y = 5  # compacter line spacing

[font]
size = 14

[font.offset]
x = 0
y = 0

[font.normal]
# family = "MesloLGS NF"
family = "JetBrainsMono Nerd Font"
# family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
# family = "MesloLGS NF"
# family = "Hack Nerd Font Mono"

[font.italic]
# family = "MesloLGS NF"
# family = "Hack Nerd Font Mono"

[font.bold_italic]
# family = "MesloLGS NF"
# family = "Hack Nerd Font Mono"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "Up"
mode = "~Vi|~Search"
mods = "Command"

# Command-Down -> PageDown - 替代 <fn - down>
[[keyboard.bindings]]
chars = "\u001B[6~"
key = "Down"
mode = "~Vi|~Search"
mods = "Command"

# Command-Left -> Home - 替代 <fn - left>
[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "~Vi|~Search"
mods = "Command"

# [[keyboard.bindings]]
# chars = "h"
# key = 0
# mods = "Option"

# Command-Right -> End - 替代 <fn - right>
[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[scrolling]
history = 100000

[window]
# decorations = "buttonless"
decorations = "full"
# decorations_theme_variant = "None"
startup_mode = "Maximized"
# option_as_alt = "Both"
option_as_alt = "OnlyLeft"
dynamic_title = false
# padding = { x = 2, y = 2 }
dynamic_padding = false
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 1
y = 1

[window.dimensions]
columns = 150
lines = 50

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"
